//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class voorraad
    {
        public int vestiging_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> aantal { get; set; }
    
        public virtual producten producten { get; set; }
        public virtual vestigingen vestigingen { get; set; }
    }
}
